### ISSUE TITLE
Docker build fails on Mac

### ISSUE THREAD

**Issue by kleinfelter** [smallwat3r/shhh#11]
I tried `docker-compose up -d --build app` on a Mac (with gcc) and it failed with

```
    unable to execute 'gcc': No such file or directory
    unable to execute 'gcc': No such file or directory
```

**Comment by kleinfelter** [comment]
I don't think this is Mac-specific.  At least one of those python modules has to be compiled.  Adding this to Dockerfile at an appropriate point cured the buildproblem.
```
RUN apt-get update
RUN apt-get -y install build-essential libffi-dev
```

**Comment by smallwat3r** [comment]
Thanks for spotting this @kleinfelter 

I switched the Docker image to Alpine:3.8 and installed the correct packages to fix this issue
