### ISSUE TITLE
Current python does not include escape in cgi

### ISSUE THREAD

**Issue by kleinfelter** [smallwat3r/shhh#12]
Python 3.8 dropped escape from cgi.  This causes client_read.py to fail.

To fix, you either need to pin your image to an older release of python:3-slim or you need to edit client_read.py and

* change 'import cgi' to 'import html'
* change 'cgi.escape' to 'html.escape'

**Comment by smallwat3r** [comment]
Thanks @kleinfelter, it has been fixed in the last commit.
