### ISSUE TITLE
Running on localhost generates bad URL

### ISSUE THREAD

**Issue by kleinfelter** [smallwat3r/shhh#13]
After making the changes mentioned in my other two issues, shhh seems to run almost correctly, but it generates a broken URL.

* The app is running on `http://localhost:5000`.
* When I tell it to generate an URL, here's a sample: `localhost/read?slug=Czp_CcREsoz-p8rkcTSMkMGDT_znzCGX7KCrosXIr5w`

I have to manually change 'localhost' to 'http://localhost:5000'.

**Comment by smallwat3r** [comment]
Thanks @kleinfelter, this has been fixed in last commit using `window.location.host`.
