### ISSUE TITLE
Vulnerability: Leaves Passwords in Browser History

### ISSUE THREAD

**Issue by kleinfelter** [smallwat3r/shhh#14]
The app leaves both the secret and the password-to-reveal-secret in the browser history.  This is not good.  After closing the tab, pressing Control+Shift+T reveals both items.  In addition, the secret and the password are left in browser storage on disk.  Scattering passwords around the file system in caches is a worst-practice.

I don't have a complete solution to offer (yet), but we need to find a way to get that confidential data out of the browser's history before this app can be considered 'safe'.

Note that this is NOT an issue of cache.  History and cache are separate mechanisms.  Even with these headers, the data is still in browser history.

```
resp.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
resp.headers['Pragma'] = 'no-cache'
resp.headers['Expires'] = '0'
```

**Comment by kleinfelter** [comment]
I *think* it is enough to edit read.html, replacing this:
```
            $('#linkSuccess').fadeIn(1000);
            $('#secretMsg').empty().append(d.msg);
            $('#decryptBtn').attr('disabled', true);
```
with this
```
            $('#linkSuccess').fadeIn(1000);
            $('#secretMsg').empty().append(d.msg);
            $('#decryptBtn').attr('disabled', true);
            $('#passPhrase').val(''); // hide the password from browser history
```

**Comment by smallwat3r** [comment]
Thanks for spotting this @kleinfelter 
Really appreciate your feedback - this has been fixed.
Also, I just did a codebase refactoring ( #15 ) to simplify the application and get rid of old code.
