### ISSUE TITLE
Feature request: Adjustable Character Limit

### ISSUE THREAD

**Issue by Jisagi** [smallwat3r/shhh#160]
Hi, I was wondering if it would be a possible to make the max char limit changeable (but leave a default value of 150). I'd love to send over certificates with shhh, but can't do it, because basically all of them are too long because of the hardcoded character limit. Being able to change it with for example an env variable would be really nice, so one can even send even a full cert chain with shhh.

This might somewhat break with the idea of the project, but I think it could be a nice addition to broaden the possibilities shhh could be used in.

**Comment by smallwat3r** [comment]
Hi @Jisagi and thanks for the suggestion! Indeed that could be a great addition to Shhh. I will start working on this when I find some spare time, this shouldn't be too difficult to implement. I will leave this issue open for the time being!

**Comment by smallwat3r** [comment]
Hi @Jisagi, I've just release a version 2.4.0 of Shhh with this new feature. 

You can now set an optional environment variable `SHHH_SECRET_MAX_LENGTH` to use a custom max length for the secrets. I've also bumped the default limit from 150 to 250 characters.

If you have any problems trying out this feature, please feel free to re-open or create a new issue.

**Comment by Jisagi** [comment]
Hi, thank you very much for the feature. Sadly I wasn't not yet able to build the newest version with docker-compose. I am getting the following error: https://pastebin.com/8yptiNX7
I am not sure if this might be a problem related to my setup, or a general problem though.
My steps to always reproduce this issue on my machine is to just clone the repository and then try, change the env vars in docker.env and the run it with `docker-compose --build -d`. I tried to clear any old images i had of shhh, but no luck either. Do you have an idea why this could happen?

**Comment by Jisagi** [comment]
I was finally able to fix the issue by adding `RUN apk add build-base` after `apk update` to the Dockerfile. Not sure if this is an isolated problem or something that might happen to others as well

**Comment by smallwat3r** [comment]
Thanks for spotting this @Jisagi, after rebuilding a local image I had the same issue.
I've pushed a fix to the Dockerfile, adding `apk add g++` should fix it.

**Comment by Jisagi** [comment]
I can confirm this as well, the standalone g++ also does the job 👍
