### ISSUE TITLE
On page character limit calculation incorrect

### ISSUE THREAD

**Issue by Jisagi** [smallwat3r/shhh#185]
Hi, I noticed, the calculation of "characters left" on the website are incorrect when newline characters are used. The backend calculation uses 2 characters for a newline, but the frontend only uses 1 character. This might also cause problems with non unicode characters, but I didn't test that.

A quick and easy/dirty fix would be to replace the any newline with two characters (e.g. empty spaces) and then calc the size. but there might be a better solution.

**Comment by smallwat3r** [comment]
Thanks for spotting this @Jisagi. This seems to behave ok on Firefox, but after trying it on Chrome I did noticed this issue.
I created #186 that should fix this issue!

**Comment by Jisagi** [comment]
Works like a charm, thank you for the fast fix
