### ISSUE TITLE
quote decode error

### ISSUE THREAD

**Issue by xoyteam** [smallwat3r/shhh#277]
![Выделение_1141](https://user-images.githubusercontent.com/7936892/177288987-2ecdbadb-8ebe-4638-a123-3100748dd079.png)

**Comment by smallwat3r** [comment]
Thanks for reporting this @xoyteam, this should be fixed in https://github.com/smallwat3r/shhh/pull/279

**Comment by xoyteam** [comment]
Thanks works fine!
