### ISSUE TITLE
ampersand decode error

### ISSUE THREAD

**Issue by prodigiosovolcan** [smallwat3r/shhh#291]
Writing an & inside de coded text is transformed into `&amp;`

<img width="861" alt="screen" src="https://user-images.githubusercontent.com/110902547/197566849-202065a5-a6e6-4b0d-ae93-8603fc70d858.png">

**Comment by smallwat3r** [comment]
Thanks for spotting this @prodigiosovolcan

This should now be fixed in https://github.com/smallwat3r/shhh/pull/293
