### ISSUE TITLE
What about mysql?

### ISSUE THREAD

**Issue by mffan0922** [smallwat3r/shhh#298]
Does this app support postgre only? mysql will be OK?
Or there is plan to fit it with mysql, thx a lot.

**Comment by smallwat3r** [comment]
@mffan0922 correct, this currently only supports Postgres.

But I don't think it would be too complex to add support for MySQL.

I can have a look at adding this in when I find some free time, so I will leave this ticket open for now

**Comment by smallwat3r** [comment]
@mffan0922 support for MySQL (and other potential other DB) has now been added from https://github.com/smallwat3r/shhh/pull/428
