### ISSUE TITLE
docker-compose is now docker compose

### ISSUE THREAD

**Issue by fyrfli** [smallwat3r/shhh#320]
Hi there.

Even though docker-compose still works in the majority of installations, some of us installed the  docker engine with compose integrated. This means the commands such as `docker-compose up -d` do not work for us. The equivalent command is `docker compose up -d`.

The Makefile uses `docker-compose`. To make it work on my server, I had to change that to `docker compose`. 

Should we accommodate that change somehow?  Whether we note it in the README/installation documentation or switch requirements to use the new docker engine with compose integrated?

**Comment by smallwat3r** [comment]
Hi @fyrfli,

That's a good point. Using `docker compose` which is a more recent version makes sense to me. Please feel free to open a pull request with this change.

An alternative in the future, if you encounter this issue in other projects, you could create an alias for `docker-compose`:

Create a file `/usr/local/bin/docker-compose` with this content:
```
docker compose --compatibility "$@"
```
Make it executable `sudo chmod +x /usr/local/bin/docker-compose`

You should then be able to use either `docker-compose` or `docker compose`

**Comment by smallwat3r** [comment]
I will now close this issue, as the Makefile has been edited to use the newer `docker compose` version as default.
