### ISSUE TITLE
Add auto destruction feature

### ISSUE THREAD

**Issue by bestlibre** [smallwat3r/shhh#44]
I'm thinking that an additional security feature could be to destroy the secret after N missed decryption attempt. N should be configurable either globally or per secret. And we also need to be able to deactivate this feature.

What are your thoughts on that?

I'm also thinking that some feature could be made configurable :

- call to ihavebeenpwded. It could be a three state switch : on, optional, off. If set to optional, the users are warned but the secret could be created
- maximum amount of time to keep the secrets. In privatebin this is a list of values.
- Security rules for the password. It is sometimes convenient to create a secret with a simple password. If the number of try can be set, the security should still be quite high.

**Comment by smallwat3r** [comment]
Thanks for these ideas, much appreciated, definitely some features I would like to implement 👍

I especially like the option of having a limited amount of tries before the secret gets destructed, making sure the app is immune from brute-force attacks.

Please let me know if you'd like / have already started working on any of these features, if not no worries, I'll add these to the backlog and will work on these when I got some time!

**Comment by bestlibre** [comment]
I haven't work on it. To be honest I'm currently testing both shhh and [ots](https://github.com/Luzifer/ots). I think I will go with ots since it has a really smaller footprint on memory. I think it is less secure (you can download the encrypted secret without the passphrase and try to bruteforce it) but its docker containers use only  8M of RAM versus 130M for shhh (120 for the app itself and 10 for the db). The footprint could probably be reduce with the use of sqlite instead of postgres but will still be quite big.

**Comment by smallwat3r** [comment]
Thanks for pointing out this project, wasn't aware of it and indeed this looks quite nice. I guess it's one of the many advantages of Go over Python :)

**Comment by smallwat3r** [comment]
Closing this issue has most of the features have been implemented in #53
