### ISSUE TITLE
deploy to Heroku button - Failing to connect to postgres

### ISSUE THREAD

**Issue by chrismalek** [smallwat3r/shhh#72]
I tried the Heroku button to deploy this and I got this error on startup during the "Run scripts & scale dynos" step.

I am looking through where that is set. It has been a while since I played with Heroku and Ruby.
```bash
FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.
Couldn't create 'd7cfcal83lp3nr' database. Please check your configuration.
rake aborted!
PG::ConnectionBad: FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege.

```

**Comment by smallwat3r** [comment]
Hi @chrismalek,

I've tried the Heroku deploy button from my side but everything seems to work as expected.
So my first thought is that the issue probably comes from your Heroku account or set-up.
What type of account are you using (personal or teams)? 
Also, do you currently have any Postgres database that you use from Heroku?

**Comment by chrismalek** [comment]
I am using the personal heroku. I don't currently have any active projects on heroku. I used to use Heroku for some stuff years ago but I transitioned that all to some other cloud providers and technology. Let me dig around Heroku to see if I need to configure that postgres before hand.

**Comment by chrismalek** [comment]
@smallwat3r I am a complete moron. Please forgive me. I was evaluating several different similar projects and I posted this to the wrong project.  Sorry to waste your time. The Deploy to Heroku for this project works perfectly...thank you..this project rocks.

**Comment by smallwat3r** [comment]
@chrismalek ahah no worries, good to hear it's working fine 😄
